### ISSUE TITLE
Using terraform.tfvars for BYOL and facing error

### ISSUE THREAD

**Issue by amitmvyas** [tylerhatton/f5-warm-pool-demo#1]
Hi,

I have used this entire deployment code as per given instructions, but facing some strange issue and couldn't find what needs to be done here.

My terraform.tvfars refer as below.

license_type                   = "BYOL"
bigiq_server                   = "x.x.x.x"
bigiq_license_pool_name        = "big-iq-lic-pool-tst"
bigiq_username_secret_location = "admin"
bigiq_password_secret_location = "abcdefghijk@123"

`
│ Error: Secrets Manager Secret "admin" Version "AWSCURRENT" not found
│
│   with module.bigip_1arm_autoscale.data.aws_secretsmanager_secret_version.bigiq_username[0],
│   on modules\bigip-1arm-autoscale\main.tf line 188, in data "aws_secretsmanager_secret_version" "bigiq_username":
│  188: data "aws_secretsmanager_secret_version" "bigiq_username" {
│
╵
╷
│ Error: Secrets Manager Secret "abcdefghijk@123" Version "AWSCURRENT" not found
│
│   with module.bigip_1arm_autoscale.data.aws_secretsmanager_secret_version.bigiq_password[0],
│   on modules\bigip-1arm-autoscale\main.tf line 193, in data "aws_secretsmanager_secret_version" "bigiq_password":
│  193: data "aws_secretsmanager_secret_version" "bigiq_password" {
`
I am missing something here ? 

Do I have to cretae  secrets in Secret Manager like these "bigiq_username" "bigiq_password" first manually and then need to provide values like below in terraform.tfvars

license_type                   = "BYOL"
bigiq_server                   = "x.x.x.x"
bigiq_license_pool_name        = "big-iq-lic-pool-tst"
bigiq_username_secret_location = "bigiq_username"
bigiq_password_secret_location = "bigiq_password"

Kindly help so i can use this code for successfuly deployment.

Regards,
Amit Vyas

**Comment by tylerhatton** [comment]
Hey Amit,

You are correct. Instead of providing the credentials for BIG-IQ in tfvars, you have to create two secrets in secrets manager for the BIG-IQ username and password and provide those for the variables. This is so runtime-init on the BIG-IP can get the credentials for licensing.

-Tyler

**Comment by amitmvyas** [comment]
Thank you for your quick revert Tyler, just a thought, what if I don't want to use AWS Secret Manager at all and just want use plan text details for BIG-IQ server details, what modfication I have to do ? or would you suggest to use AWS Secret Manager as default ?

Regards,
Amit Vyas

**Comment by tylerhatton** [comment]
I would encourage you to use Secrets Manager as it prevents your BIG-IQ password from being stored as plaintext in potentially your Terraform state and user data contents you are passing to the BIG-IPs.

If you want to hard code the username and password, you can modify the user_data.tpl file that provides to runtime-init configurations for BIG-IQ licensing.

Remove lines 26-41 here:
https://github.com/tylerhatton/f5-warm-pool-demo/blob/e72ffe865b8177550f862e6729333b9057757d82/modules/bigip-1arm-autoscale/templates/user_data.tpl#L26-L41

You can then hard code the plaintext username and password in parameters here:
https://github.com/tylerhatton/f5-warm-pool-demo/blob/e72ffe865b8177550f862e6729333b9057757d82/modules/bigip-1arm-autoscale/templates/user_data.tpl#L87-L88

**Comment by amitmvyas** [comment]
Thank you so much Tyler for your swift response !
